# Generated by Django 3.1.5 on 2021-02-22 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_date',
            field=models.DateField(auto_now=True),
        ),
    ]
