# Generated by Django 3.1.5 on 2021-02-27 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='img_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_date',
            field=models.DateField(default=datetime.date(2021, 2, 27)),
        ),
    ]
