# Generated by Django 3.1.5 on 2021-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
