# Generated by Django 3.1.5 on 2021-02-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0002_auto_20210222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='img',
        ),
    ]
