# Generated by Django 3.1.5 on 2021-02-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0003_auto_20210227_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='name',
            new_name='product_name',
        ),
    ]
