# Generated by Django 3.1.5 on 2021-03-03 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0003_auto_20210302_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_date',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
    ]
