# Generated by Django 3.1.5 on 2021-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0003_remove_product_details_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='category',
            field=models.CharField(default='Z', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_date',
            field=models.DateField(),
        ),
    ]
