# Generated by Django 3.1.5 on 2021-02-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0004_auto_20210227_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='images',
            new_name='image',
        ),
    ]
