# Generated by Django 3.1.5 on 2021-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0005_auto_20210227_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
