# Generated by Django 3.1.5 on 2021-03-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_details',
            name='price',
        ),
    ]
