# Generated by Django 3.1.5 on 2021-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedproduct',
            name='seller_email',
            field=models.CharField(max_length=100),
        ),
    ]
