# Generated by Django 3.1.5 on 2021-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0002_remove_cart_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedproduct',
            name='seller_email',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedproduct',
            name='seller_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
