# Generated by Django 3.1.5 on 2021-02-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0003_auto_20210224_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedproduct',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='receivedproduct',
            old_name='product_price',
            new_name='price',
        ),
    ]
