# Generated by Django 3.1.5 on 2021-02-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0004_auto_20210224_1815'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receivedproduct',
            table=None,
        ),
    ]
