# Generated by Django 3.1.5 on 2021-02-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0006_auto_20210224_2121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receivedproduct',
            table='receivedProducts',
        ),
    ]
