# Generated by Django 3.1.5 on 2021-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0007_auto_20210224_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedproduct',
            name='images',
        ),
    ]
