# Generated by Django 3.1.5 on 2021-02-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0008_remove_receivedproduct_images'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receivedproduct',
            table=None,
        ),
    ]
