# Generated by Django 3.1.5 on 2021-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0009_auto_20210224_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedproduct',
            name='images',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
