# Generated by Django 3.1.5 on 2021-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_home', '0010_receivedproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedproduct',
            name='images',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterModelTable(
            name='receivedproduct',
            table='receivedproduct',
        ),
    ]
