# Generated by Django 3.1.5 on 2021-02-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='id',
            new_name='product_id',
        ),
    ]
