# Generated by Django 3.1.5 on 2021-02-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='account',
        ),
    ]
